apiVersion: apps/v1  #kubectl api-versions 可以通过这条指令去看版本信息
kind: Deployment # 指定资源类别
metadata: #资源的一些元数据
  name: blogapp #deloyment的名称
  labels:
    app: blogapp  #标签
spec:
  replicas: 2 #创建pod的个数
  selector:
    matchLabels:
      app: blogapp #满足标签为这个的时候相关的pod才能被调度到
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
        - name: blogapp
          image: registry.cn-qingdao.aliyuncs.com/idea_hub/idea_resp:1.0
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888